CloneCrm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
   # path('', include('common.urls', namespace="Common")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    # path('contacts/', include('contacts.urls', namespace="contacts")),
    # path('opportunities/', include('opportunity.urls', namespace="opportunities")),
    # path('cases/', include('cases.urls', namespace="cases")),
]

cases/urls.py
from django.urls import path
from cases.views import (CasesListView, CreateCaseView, UpdateCaseView, DeleteCaseView, DetailCaseView)
from . import views

app_name  = 'cases'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', CasesListView.as_view(), name='list'),
    path('create/', CreateCaseView.as_view(), name='create'),
    path('<int:pk>/update/', UpdateCaseView.as_view(), name='update'),
    path('<int:pk>/delete/', DeleteCaseView.as_view(), name='delete'),
    path('<int:pk>/detail/', DetailCaseView.as_view(), name='detail'),
]

cases/models.py
"""
Case: thông tin của một task.

"""

from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from common.utils import    CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE
from accounts.models import Account
from contacts.models import Contact
from common.models import Team
from planner.models import Event

# Create your models here.
class Case(models.Model):
    """
        Thông tin về Case (một task)
        name: tên case
        status: trạng thái của case. Là giá trị kiểu enum: STATUS_CHOICE
        priority: mực độ ưu tiên của case
        case_type: phân loại case: giá trị kiểu enum: CASE_TYPE
        account: account liên quan tới case. một accout có thể có nhiều case. vì vậy quan hệ ở đây là many-to-one
        contacts: contacts liên quan tới case. một contact có thể có nhiều case. một case có thể liên quan nhiều contact. Quan hệ
        ở đây là many-to-many
        closed_on: thời gian case được đóng
        description: mô tả thêm về case
        assigned_to: user được phân công cho case. Một user có thể được giao nhiều case. Một case có thể được giao cho nhiều user. Vì
        vậy quan hệ ở đây là many-to-many
        teams: team liên quan đến case:Quan hệ many-to-many
        created_by: User tạo case. Một user có thể tạo nhiều case. Quan hệ many-to-one
        created_on: thời gian tạo case.
        is_active: trạng thái của case


    """
    name = models.CharField(pgettext_lazy("name of the case", "Name"), max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64, blank=True, null=True)
    case_type = models.CharField(choices=CASE_TYPE, max_length=255, blank=True, null=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null = True)
    contacts = models.ManyToManyField(Contact)
    closed_on = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='case_assigned_user')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='case_created_by', on_delete=models.CASCADE, blank=True, null=True)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']
    
    def __str__(self):
        return self.name

    def get_meetings(self):
        """
            get meeting event
        """
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting", status="Planned")

    def get_completed_meetings(self):
        # get cuộc họp đã hoàn thành
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        # get task đang trạng thái planned
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Task", status="Planned")

    def get_completed_tasks(self):
        # get task đã hoàn thành
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task").exclude(status="Planned")

    def get_calls(self):
        # get cuộc gọi trạng thái planned
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Call", status="Planned")

    def get_completed_calls(self):
        # get cuộc gọi đã hoàn thành
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        # get user được phân công task
        return User.objects.get(id=self.assigned_to.id)

cases/views.py
"""
Thông tin các view cơ bản
index: view này để import thông tin từ file datatest vào trong database
CasesListView: hiển thị danh sách các case
CreateCaseView: cho phép tạo một case mới
UpdateCaseView: cho phép cập nhật thông tin cho case
DetailCaseView: hiển thị thông tin chi tiết cho một case
DeleteCaseView: xóa một case
"""
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.shortcuts import render
from django.views.generic import (CreateView, UpdateView, DetailView, ListView, DeleteView, TemplateView)
from django.template import loader
from django.contrib.auth.models import User
from django.db.models import Q
import openpyxl
from phonenumber_field.modelfields import PhoneNumberField

from .models import Case
from accounts.forms import AccountForm
from .forms import CaseForm
from common.models import Address, Team, Comment, Attachments
from common.utils import  INDCHOICES, COUNTRIES, CURRENCY_CODES, CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE, LEAD_STATUS
from opportunity.models import Opportunity, STAGES, SOURCES
from common.forms import BillingAddressForm, ShippingAddressForm
from contacts.models import Contact
from cases.models import Case
from opportunity.models import Opportunity
from accounts.models import Account
from planner.models import Event
# Create your views here.


def FindCaseByName(tenCongViec):
    """ Tìm kiếm case bởi tên ten
    return None nếu không tìm thấy
    Ngược lại trả về một object
    """
    cases = Case.objects.filter(name=tenCongViec)
    if cases.count() == 0:
        return None
    return cases[0]

def AddTeam(ten):
    """ taọ một team mới
    Nếu team đã tồn tại thì return team
    ngược lại thì tạo mới và return team đó
    """
    teams = Team.objects.filter(name = ten)
    if teams.count() == 0:
        team = Team(name=ten)
        team.save()
        return team
    
    else:
        return teams[0]

def AddAccount(name):
    """
    tạo mot accout
    """
    account = Account(name = name)
    return account


def AddContact(ten):
    """ taọ một contact mới
    Nếu contact đã tồn tại thì return contact
    ngược lại thì tạo mới và return contact đó
    """
    contacts = Contact.objects.filter(first_name = ten)
    if contacts.count() == 0:
        contact = Contact(first_name=ten)
        contact.save()
        return contact
    
    else:
        return contacts[0]

def AddCase(row_data):
    """
    create Case từ một row data trong file
    """
    stt = row_data[0]
    name = row_data[1]
    status = row_data[2]
    priority = row_data[3]
    case_type = row_data[4]
    accountName = row_data[5]
    contact = row_data[6]
    description = row_data[7]
    assigned_to = row_data[8]
    teamName = row_data[9]
   
    case = FindCaseByName(name)
    if case is None:
        case = Case()
    
    team = AddTeam(teamName)
    account = AddAccount(accountName)
    contact = AddContact(contact)
    #update thông tin case
    case.name = name
    case.status = status
    case.priority = priority
    case.case_type = case_type
    case.description = description
    case.account = account
    case.created_by = User.objects.get(pk=1)
    case.save()
    case.teams.add(team)
    case.contacts.add(contact)
def index(request):
    if "GET" ==  request.method: 
        return render(request, 'cases/index_case.html', {})
    else:
        excel_file = request.FILES["excel_file"]

        wb = openpyxl.load_workbook(excel_file, data_only=True)

        worksheet = wb["Sheet1"]
        excel_data = list()

        #loop over all row in file
        index = 0
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:

                row_data.append(str(cell.value))
            if index > 0:
                AddCase(row_data)

            index = index + 1
            excel_data.append(row_data)
        return render(request, 'cases/index_case.html', {"excel_data":excel_data})


class CasesListView(TemplateView):
    model = Case
    context_object_name = "cases_list"
    template_name = "cases/list_cases.html"

    def get_queryset(self):
        queryset = self.model.objects.all().select_related("address").order_by('id')

        request_post = self.request.POST
        if request_post:
            #loc dữ liệu theo name
            if request_post.get('first_name'):
                queryset = queryset.filter(name__icontains=request_post.get('first_name'))
            # lọc dữ liệu theo city
            if request_post.get('city'):
                queryset = queryset.filter(
                    billing_address__in=[i.id for i in Address.objects.filter(
                        city__contains=request_post.get('city'))])
            # lọc dữ liệu theo industry
            if request_post.get('status'):
                queryset = queryset.filter(industry__icontains=request_post.get('status'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CasesListView, self).get_context_data(**kwargs)
        context["cases_list"] = self.get_queryset()
        context["industries"] = INDCHOICES
        context["per_page"] = self.request.POST.get('per_page')
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

class CreateCaseView(CreateView):
    model = Case
    form_class = AccountForm
    template_name  = "accounts/create_account.html"
    def dispatch(self, request, *args, **kwargs):
        self.users = User.objects.filter(is_active=True).order_by('email')
        return super(CreateCaseView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(CreateCaseView, self).get_form_kwargs()
        kwargs.update({'assigned_to': self.users})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        billing_form = BillingAddressForm(request.POST)
        shipping_form = ShippingAddressForm(request.POST, prefix='ship')
        if form.is_valid() and billing_form.is_valid() and shipping_form.is_valid():
            return self.form_valid(form, billing_form, shipping_form)
        else:
            return self.form_invalid(form, billing_form, shipping_form)

    def form_valid(self, form, billing_form, shipping_form):
        # Save Billing & Shipping Address
        billing_address_object = billing_form.save()
        shipping_address_object = shipping_form.save()
        # Save Account
        account_object = form.save(commit=False)
        account_object.billing_address = billing_address_object
        account_object.shipping_address = shipping_address_object
        account_object.created_by = self.request.user
        account_object.save()
        if self.request.POST.getlist('assigned_to', []):
            account_object.assigned_to.add(*self.request.POST.getlist('assigned_to'))
            assigned_to_list = self.request.POST.getlist('assigned_to')
            current_site = get_current_site(self.request)
            for assigned_to_user in assigned_to_list:
                user = get_object_or_404(User, pk=assigned_to_user)
                mail_subject = 'Assigned to account.'
                message = render_to_string('assigned_to/account_assigned.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'protocol': self.request.scheme,
                    'account': account_object
                })
                email = EmailMessage(mail_subject, message, to=[user.email])
                email.send()
        if self.request.POST.getlist('teams', []):
            account_object.teams.add(*self.request.POST.getlist('teams'))
        if self.request.POST.get("savenewform"):
            return redirect("accounts:new_account")
        else:
            return redirect("accounts:list")

    def form_invalid(self, form, billing_form, shipping_form):
        return self.render_to_response(
            self.get_context_data(
                form=form, billing_form=billing_form, shipping_form=shipping_form)
        )

    def get_context_data(self, **kwargs):
        context = super(CreateCaseView, self).get_context_data(**kwargs)
        context["account_form"] = context["form"]
        context["users"] = self.users
        context["industries"] = INDCHOICES
        context["countries"] = COUNTRIES
        context["teams"] = Team.objects.all()
        if "billing_form" in kwargs and "shipping_form" in kwargs:
            context["billing_form"] = kwargs["billing_form"]
            context["shipping_form"] = kwargs["shipping_form"]
        else:
            if self.request.POST:
                context["billing_form"] = BillingAddressForm(self.request.POST)
                context["shipping_form"] = ShippingAddressForm(self.request.POST, prefix='ship')
            else:
                context["billing_form"] = BillingAddressForm()
                context["shipping_form"] = ShippingAddressForm(prefix='ship')
        context["assignedto_list"] = [
            int(i) for i in self.request.POST.getlist('assigned_to', []) if i]
        context["teams_list"] = [
            int(i) for i in self.request.POST.getlist('teams', []) if i]
        return context

class DetailCaseView(DetailView):
    model = Case
    context_object_name = "case_record"
    template_name = "cases/view_case.html"

    def get_context_data(self, **kwargs):
        context = super(DetailCaseView, self).get_context_data(**kwargs)
        comments = Comment.objects.filter(case_id=self.object.id).order_by('-id')

cases/templates/cases/index_case.html
<html>

    <head>

        <title>

            Excel file upload and processing : Django Example : ThePythonDjango.Com

        </title>

    </head>

    <body style="margin-top: 30px;margin-left: 30px;">

        <form action="{% url "leads:index" %}" method="post" enctype="multipart/form-data">

            {% csrf_token %}

            <input type="file"

                   title="Upload excel file"

                   name="excel_file"

                   style="border: 1px solid black; padding: 5px;"

                   required="required">

            <p>

            <input type="submit"

                   value="Upload"

                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">

        </form>



        <p></p>

        <hr>



        {% for row in excel_data %}

            {% for cell in row %}

                {{ cell }}&nbsp;&nbsp;

            {% endfor %}

            <br>

        {% endfor %}

    </body>

</html>

cases/templates/cases/list_cases.html
{% extends "base.html" %}

{% load static %}
{% load paginate %}
{% block body_class %}template-homepage{% endblock %}



{% block content %}

<div class="row">
    <div class="col-md-12">
        <!-- DATA TABLE -->
        <h3 class="title-5 m-b-35">data table</h3>
        <div class="table-data__tool">
            <div class="table-data__tool-left">
                <div class="rs-select2--light rs-select2--md">
                    <select class="js-select2" name="property">
                        <option selected="selected">All Properties</option>
                        <option value="">Option 1</option>
                        <option value="">Option 2</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
                <div class="rs-select2--light rs-select2--sm">
                    <select class="js-select2" name="time">
                        <option selected="selected">Today</option>
                        <option value="">3 Days</option>
                        <option value="">1 Week</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
                <button class="au-btn-filter">
                    <i class="zmdi zmdi-filter-list"></i>filters</button>
            </div>
            <div class="table-data__tool-right">
                <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{% url 'cases:create' %}">
                    <i class="zmdi zmdi-plus"></i>add item</a>
                <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                    <select class="js-select2" name="type">
                        <option selected="selected">Export</option>
                        <option value="">Option 1</option>
                        <option value="">Option 2</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
            </div>
        </div>
        <div class="table-responsive table-responsive-data2">
            <table class="table table-data2">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>email</th>
                        <th>Status</th>
                        <th>Created on</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                        {% if per_page %}
                        {% paginate per_page cases_list %}
                      {% else%}
                        {% paginate 10 cases_list %}
                      {% endif %}
                      
                    {% for lead in cases_list %}
                    <tr class="tr-shadow">
                        <td>{{ lead.id }}</td>
                        <td>{{ lead.first_name }}</td>
                        <td>
                            <span class="block-email">{{ lead.email }}</span>
                        </td>
                        <td>{{ lead.status }}</td>
                        <td>{{ lead.created_on }}</td>
                      
                        <td>
                            <div class="table-data-feature">
                                <a class="item" data-toggle="tooltip" data-placement="top" title="Send" href="#">
                                    <i class="zmdi zmdi-mail-send"></i>
                                </a>
                                <a class="item" data-toggle="tooltip" data-placement="top" title="Edit" href="{% url 'cases:update' lead.id %}">
                                    <i class="zmdi zmdi-edit"></i>
                                </a>
                                <a class="item" data-toggle="tooltip" data-placement="top" title="Delete" href="{% url 'cases:delete' lead.id %}">
                                    <i class="zmdi zmdi-delete"></i>
                                </a>
                                <a class="item" data-toggle="tooltip" data-placement="top" title="More" href="{% url 'cases:detail' lead.id %}">
                                    <i class="zmdi zmdi-more"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    <tr class="spacer"></tr>
                   {% endfor %}
                </tbody>
            </table>
            {% ifequal cases_list|length 0 %}
            <h6 class="text-center">No Leads Records Found</h6>
          {% endifequal %}
          <div class="text-center row marl">
            {% show_pages %}
          </div>
        </div>
        <!-- END DATA TABLE -->
    </div>
</div>
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $('.item').click(function(e){
    if ($(this).children(":first").attr('class') == "zmdi zmdi-delete") {
          e.preventDefault()
          url = $(this).attr('href')
          if (!confirm('Are you sure you want to delete?'))
              return;
          window.location = $(this).attr('href')
      }
    
  });
  </script>
  {% endblock js_block %}

cases/templates/cases/view_case.html
{% extends "base.html" %}

{% load static %}

{% block body_class %}template-homepage{% endblock %}



{% block content %}
<div class="row">

    <div class="col-lg-12">

        <form action="" method="post" novalidate="novalidate">
            <div class="card">

                <div class="card-body">

                    <div class="card-title">

                        <h3 class="text-center title-2">Thông tin lead</h3>

                    </div>

                    <hr>

                    <div class="row">

                        <div class="col-lg-6">

                            <h4>Name</h4>

                            <label  class="control-label mb-1">{{ lead_record.first_name }} {{ lead_record.last_name }}</label>
                            {% if lead_record.account_name %}
                            <h4>Account Name</h4>
                            
                            <label  class="control-label mb-1">{{ lead_record.account_name }}</label>
                            {% endif %}
                            {% if lead_record.title %}
                            <h4>Title</h4>
                            
                            <label  class="control-label mb-1">{{ lead_record.title }}</label>
                            {% endif %}
                            <h4>Phone</h4>

                            <label  class="control-label mb-1">{{ lead_record.phone }}</label>

                            <h4>email</h4>

                            <label  class="control-label mb-1">{{ lead_record.email }}</label>
                            <h4>Status</h4>

                            <label class="control-label mb-1">{{ lead_record.status }}</label>

                            <h4>Source</h4>

                            <label class="control-label mb-1">{{ lead_record.source }}</label>

                            {% if lead_record.description %}
                            <h4>Description</h4>

                            <label for="cc-number" class="control-label mb-1">{{ lead_record.description }}</label>
                            {% endif %}
                      

                            {% if lead_record.address.address_line or lead_record.address.street or lead_record.address.city or lead_record.address.state or lead_record.address.postcode or lead_record.address.country %}

                            <h4>Billing Address</h4>

                            <label class="control-label mb-1">{{ lead_record.address.get_complete_address }}</label>
                            {% endif %}
                        </div>
                      
                        <div class="col-lg-12">
                                <label class="control-label mb-1">Created by
                                    <b>{{ lead_record.created_by }}</b> 
                                    created on
                                    <i>
                                        <b>
                                                {{ lead_record.created_on }}
                                        </b>

                                    </i>
                                </label>
                        </div>
                    </div>





                </div>

                <!-- button area  -->

                <!-- <div class="card-footer">

                    <button type="submit" class="btn btn-primary btn-sm">

                        <i class="fa fa-dot-circle-o"></i> Submit

                    </button>

                    <button type="reset" class="btn btn-danger btn-sm">

                        <i class="fa fa-ban"></i> Reset

                    </button>

                </div> -->

            </div>

        </form>

    </div>

</div>

{% endblock %}