CloneCrm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
   # path('', include('common.urls', namespace="Common")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    # path('contacts/', include('contacts.urls', namespace="contacts")),
    # path('opportunities/', include('opportunity.urls', namespace="opportunities")),
    # path('cases/', include('cases.urls', namespace="cases")),
]

accounts/urls.py
from django.urls import path
from accounts.views import (AccountsListView, CreateAccountView, UpdateAccountView, DeleteAccountView, DetailAccountView)
from . import views

app_name  = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', AccountsListView.as_view(), name='list'),
    path('create/', CreateAccountView.as_view(), name='create'),
    path('<int:pk>/update/', UpdateAccountView.as_view(), name='update'),
    path('<int:pk>/delete/', DeleteAccountView.as_view(), name='delete'),
    path('<int:pk>/detail/', DetailAccountView.as_view(), name='detail'),
]

cases/urls.py
from django.urls import path
from cases.views import (CasesListView, CreateCaseView, UpdateCaseView, DeleteCaseView, DetailCaseView)
from . import views

app_name  = 'cases'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', CasesListView.as_view(), name='list'),
    path('create/', CreateCaseView.as_view(), name='create'),
    path('<int:pk>/update/', UpdateCaseView.as_view(), name='update'),
    path('<int:pk>/delete/', DeleteCaseView.as_view(), name='delete'),
    path('<int:pk>/detail/', DetailCaseView.as_view(), name='detail'),
]

accounts/models.py
"""
account: thông tin của khách hàng, đối tác. Account đại diện cho công ty.

"""
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from common.utils import INDCHOICES
from common.models import Address, Team
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.


class Account(models.Model):
    """
        Thông tin về Account
        name: tên Account
        email: địa chỉ Email
        phone: số điện thoại liên lạc
        industry: lĩnh vực làm việc
        billing_address: địa chỉ hóa đơn
        shipping_address: địa chỉ ship hàng
        website: địa chỉ website của công ty
        description: mô tả thêm thông tin về Account
        assigned_to: User được phân công làm việc với Account
        teams: team liên quan đến Account
        created_by: User đã tạo account
        created_on: thời gian tạo account
        is_active: trạng thái của account

    """
    name = models.CharField(pgettext_lazy("Name of Account", "Name"), max_length=64)
    email = models.EmailField()
    phone = PhoneNumberField(null=True)
    industry = models.CharField(_("Industry Type"), max_length=255, choices=INDCHOICES, blank=True, null= True)
    billing_address = models.ForeignKey(Address, related_name='account_billing_address', blank=True, null=True, on_delete=models.CASCADE)
    shipping_address = models.ForeignKey(Address, related_name='acount_shipping_address', on_delete=models.CASCADE, blank=True, null=True)
    website = models.URLField(_("Website"), blank=True, null = True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='account_assigned_to')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='account_created_by', blank=True, null=True, on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created_on']

accounts/forms.py
from django import forms
from .models import Account
from common.models import Comment, Attachments


class AccountForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        super(AccountForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({'rows': '8'})
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        for key, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.label

    class Meta:
        model = Account
        fields = ('assigned_to', 'teams', 'name', 'phone', 'email', 'website', 'industry',
                  'billing_address', 'shipping_address', 'description')


class AccountCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'account', 'commented_by')


class AccountAttachmentForm(forms.ModelForm):
    attachment = forms.FileField(max_length=1001, required=True)

    class Meta:
        model = Attachments
        fields = ('attachment', 'account')

accounts/views.py
"""
Thông tin các view cơ bản
index: view này để import thông tin từ file datatest vào trong database
AccountsListView: hiển thị danh sách các account
CreateAccountView: cho phép tạo một account mới
UpdateAccoutView: cho phép cập nhật thông tin cho account
DetailAccountView: hiển thị thông tin chi tiết cho một account
DeleteAccountView: xóa một account
"""
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.shortcuts import render
from django.views.generic import (CreateView, UpdateView, DetailView, ListView, DeleteView, TemplateView)
from django.template import loader
from django.contrib.auth.models import User
import openpyxl

from .models import Account
from .forms import AccountForm
from common.models import Address, Team
from common.utils import  INDCHOICES, COUNTRIES, CURRENCY_CODES, CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE
from opportunity.models import Opportunity, STAGES, SOURCES
from common.forms import BillingAddressForm, ShippingAddressForm
from contacts.models import Contact
from cases.models import Case
from opportunity.models import Opportunity
# Create your views here.


def FindAccountByTenKhachHang(tenKhachHang):
    """ Tìm kiếm account bởi tên khách hàng
    return None nếu không tìm thấy
    Ngược lại trả về một object
    """
    khachHangs = Account.objects.filter(name=tenKhachHang)
    if khachHangs.count() == 0:
        return None
    return khachHangs[0]

def AddAddress(diachi):
    """ tạo một địa chỉ mới
    Thêm địa chỉ mới vào trong database
    trả về địa chỉ được tạo

    """
    address = Address(address_line = diachi)
    address.save()
    return address

def AddTeam(ten):
    """ taọ một team mới
    Nếu team đã tồn tại thì return team
    ngược lại thì tạo mới và return team đó
    """
    teams = Team.objects.filter(name = ten)
    if teams.count() == 0:
        team = Team(name=ten)
        team.save()
        return team
    
    else:
        return teams[0]


def AddAccount(row_data):
    """
    create Account từ một row data trong file
    """
    stt = row_data[0]
    tenkhachhang = row_data[1]
    email = row_data[2]
    dienthoai = row_data[3]
    industry = row_data[4]
    bill_diachi = row_data[5]
    ship_diachi = row_data[6]
    assigned_to = row_data[7]
    teamName = row_data[8]
    website = row_data[9]
    account = FindAccountByTenKhachHang(tenkhachhang)
    if account is None:
        account = Account()
    
    bill_address = AddAddress(bill_diachi)
    ship_address = AddAddress(ship_diachi)
    team = AddTeam(teamName)
    #update thông tin acccount
    account.name = tenkhachhang
    account.email = email
    account.phone = dienthoai
    account.industry = industry
    account.billing_address = bill_address
    account.ship_address = ship_address
    account.website = website
    account.created_by = User.objects.get(pk=1)
    account.save()
    account.teams.add(team)

def index(request):
    if "GET" ==  request.method: 
        return render(request, 'accounts/index_account.html', {})
    else:
        excel_file = request.FILES["excel_file"]

        wb = openpyxl.load_workbook(excel_file, data_only=True)

        worksheet = wb["Sheet1"]
        excel_data = list()

        #loop over all row in file
        index = 0
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:

                row_data.append(str(cell.value))
            if index > 0:
                AddAccount(row_data)

            index = index + 1
            excel_data.append(row_data)
        return render(request, 'accounts/index_account.html', {"excel_data":excel_data})


class AccountsListView(TemplateView):
    model = Account
    context_object_name = "accounts_list"
    template_name = "accounts/list_accounts.html"

    def get_queryset(self):
        queryset = self.model.objects.all().select_related("billing_address").order_by('id')

        request_post = self.request.POST
        if request_post:
            #loc dữ liệu theo name
            if request_post.get('name'):
                queryset = queryset.filter(name__icontains=request_post.get('name'))
            # lọc dữ liệu theo city
            if request_post.get('city'):
                queryset = queryset.filter(
                    billing_address__in=[i.id for i in Address.objects.filter(
                        city__contains=request_post.get('city'))])
            # lọc dữ liệu theo industry
            if request_post.get('industry'):
                queryset = queryset.filter(industry__icontains=request_post.get('industry'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(AccountsListView, self).get_context_data(**kwargs)
        context["accounts_list"] = self.get_queryset()
        context["industries"] = INDCHOICES
        context["per_page"] = self.request.POST.get('per_page')
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

class CreateAccountView(CreateView):
    model = Account
    form_class = AccountForm
    template_name  = "accounts/create_account.html"
    def dispatch(self, request, *args, **kwargs):
        self.users = User.objects.filter(is_active=True).order_by('email')
        return super(CreateAccountView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        # set giá trị cho 'assigned_to' của kwargs
        kwargs = super(CreateAccountView, self).get_form_kwargs()
        kwargs.update({'assigned_to': self.users})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        billing_form = BillingAddressForm(request.POST)
        shipping_form = ShippingAddressForm(request.POST, prefix='ship')
        if form.is_valid(): #and billing_form.is_valid() and shipping_form.is_valid():
            print("form valid")
            
            return self.form_valid(form, billing_form, shipping_form)
        else:
            print("form invalid")
            print(form.errors)
            # for field, errors in form.errors.items:
            #     for error in errors:
            #         print(field, error)


            return self.form_invalid(form, billing_form, shipping_form)

    def form_valid(self, form, billing_form, shipping_form):
        # Save Billing & Shipping Address
        billing_address_object = billing_form.save()
        shipping_address_object = shipping_form.save()
        # Save Account
        account_object = form.save(commit=False)
        account_object.billing_address = billing_address_object
        account_object.shipping_address = shipping_address_object
        account_object.created_by = self.request.user
        account_object.save()
        if self.request.POST.getlist('assigned_to', []):
            account_object.assigned_to.add(*self.request.POST.getlist('assigned_to'))
            assigned_to_list = self.request.POST.getlist('assigned_to')
            current_site = get_current_site(self.request)
            for assigned_to_user in assigned_to_list:
                user = get_object_or_404(User, pk=assigned_to_user)
                mail_subject = 'Assigned to account.'
                message = render_to_string('assigned_to/account_assigned.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'protocol': self.request.scheme,
                    'account': account_object
                })
                email = EmailMessage(mail_subject, message, to=[user.email])
                email.send()
        if self.request.POST.getlist('teams', []):
            account_object.teams.add(*self.request.POST.getlist('teams'))
        if self.request.POST.get("savenewform"):
            return redirect("accounts:new_account")
        else:
            return redirect("accounts:list")

    def form_invalid(self, form, billing_form, shipping_form):
        return self.render_to_response(
            self.get_context_data(
                form=form, billing_form=billing_form, shipping_form=shipping_form)
        )

    def get_context_data(self, **kwargs):
        context = super(CreateAccountView, self).get_context_data(**kwargs)
        context["account_form"] = context["form"]
        context["users"] = self.users
        context["industries"] = INDCHOICES
        context["countries"] = COUNTRIES
        context["teams"] = Team.objects.all()
        if "billing_form" in kwargs and "shipping_form" in kwargs:
            context["billing_form"] = kwargs["billing_form"]
            context["shipping_form"] = kwargs["shipping_form"]
        else:
            if self.request.POST:
                context["billing_form"] = BillingAddressForm(self.request.POST)
                context["shipping_form"] = ShippingAddressForm(self.request.POST, prefix='ship')
            else:
                context["billing_form"] = BillingAddressForm()
                context["shipping_form"] = ShippingAddressForm(prefix='ship')
        context["assignedto_list"] = [
            int(i) for i in self.request.POST.getlist('assigned_to', []) if i]
        context["teams_list"] = [
            int(i) for i in self.request.POST.getlist('teams', []) if i]
        return context

class DetailAccountView(DetailView):
    model = Account
    context_object_name = "account_record"
    template_name = "accounts/view_account.html"

    def get_context_data(self, **kwargs):
        context = super(DetailAccountView, self).get_context_data(**kwargs)

accounts/templates/accounts/index_account.html
<html>

    <head>

        <title>

            Excel file upload and processing : Django Example : ThePythonDjango.Com

        </title>

    </head>

    <body style="margin-top: 30px;margin-left: 30px;">

        <form action="{% url "accounts:index" %}" method="post" enctype="multipart/form-data">

            {% csrf_token %}

            <input type="file"

                   title="Upload excel file"

                   name="excel_file"

                   style="border: 1px solid black; padding: 5px;"

                   required="required">

            <p>

            <input type="submit"

                   value="Upload"

                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">

        </form>



        <p></p>

        <hr>



        {% for row in excel_data %}

            {% for cell in row %}

                {{ cell }}&nbsp;&nbsp;

            {% endfor %}

            <br>

        {% endfor %}

    </body>

</html>

accounts/templates/accounts/list_accounts.html
{% extends "base.html" %}

{% load static %}
{% load paginate %}
{% block body_class %}template-homepage{% endblock %}



{% block content %}

<div class="row">
    <div class="col-md-12">
        <!-- DATA TABLE -->
        <h3 class="title-5 m-b-35">data table</h3>
        <div class="table-data__tool">
            <div class="table-data__tool-left">
                <div class="rs-select2--light rs-select2--md">
                    <select class="js-select2" name="property">
                        <option selected="selected">All Properties</option>
                        <option value="">Option 1</option>
                        <option value="">Option 2</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
                <div class="rs-select2--light rs-select2--sm">
                    <select class="js-select2" name="time">
                        <option selected="selected">Today</option>
                        <option value="">3 Days</option>
                        <option value="">1 Week</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
                <button class="au-btn-filter">
                    <i class="zmdi zmdi-filter-list"></i>filters</button>
            </div>
            <div class="table-data__tool-right">
                <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{% url 'accounts:create' %}">
                    <i class="zmdi zmdi-plus"></i>add item</a>
                <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                    <select class="js-select2" name="type">
                        <option selected="selected">Export</option>
                        <option value="">Option 1</option>
                        <option value="">Option 2</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
            </div>
        </div>
        <div class="table-responsive table-responsive-data2">
            <table class="table table-data2">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>email</th>
                        <th>City</th>
                        <th>Industry</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                        {% if per_page %}
                        {% paginate per_page accounts_list %}
                      {% else%}
                        {% paginate 10 accounts_list %}
                      {% endif %}
                      
                    {% for account in accounts_list %}
                    <tr class="tr-shadow">
                        <td>{{ account.id }}</td>
                        <td>{{ account.name }}</td>
                        <td>
                            <span class="block-email">{{ account.email }}</span>
                        </td>
                        <td>{{ account.billing_address.city }}</td>
                        <td>{{ account.industry }}</td>
                      
                        <td>
                            <div class="table-data-feature">
                                <a class="item" data-toggle="tooltip" data-placement="top" title="Send" href="#">
                                    <i class="zmdi zmdi-mail-send"></i>
                                </a>
                                <a class="item" data-toggle="tooltip" data-placement="top" title="Edit" href="{% url 'accounts:update' account.id %}">
                                    <i class="zmdi zmdi-edit"></i>
                                </a>
                                <a class="item" data-toggle="tooltip"  data-placement="top" title="Delete" href="{% url 'accounts:delete' account.id %}">
                                    <i class="zmdi zmdi-delete"></i>
                                </a>
                                <a class="item" data-toggle="tooltip" data-placement="top" title="More" href="{% url 'accounts:detail' account.id %}">
                                    <i class="zmdi zmdi-more"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    <tr class="spacer"></tr>
                   {% endfor %}
                </tbody>
            </table>
            {% ifequal accounts_list|length 0 %}
            <h6 class="text-center">No Acccount Records Found</h6>
          {% endifequal %}
          <div class="text-center row marl">
            {% show_pages %}
          </div>
        </div>
        <!-- END DATA TABLE -->
    </div>
</div>
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $('.item').click(function(e){
    if ($(this).children(":first").attr('class') == "zmdi zmdi-delete") {
          e.preventDefault()
          url = $(this).attr('href')
          if (!confirm('Are you sure you want to delete?'))
              return;
          window.location = $(this).attr('href')
      }
    
  });
  </script>
  {% endblock js_block %}